### PR TITLE
Add DARPA acknowledgment to README

### PR DESCRIPTION
**Pull request by waxlamp**

### CODE REVIEW

**Comment by cfunk1210** [comment]
This is just for SAIL-ON.  You also need one for Learn/LwLL.  Please add this.  

LwLL
This material is based on research sponsored by DARPA under agreement number FA8750-19-1-0504. The U.S. Government
is authorized to reproduce and distribute reprints for Governmental purposes notwithstanding any copyright notation
thereon.

**Comment by waxlamp** [comment]
> This is just for SAIL-ON. You also need one for Learn/LwLL. Please add this.
> 
> LwLL
> This material is based on research sponsored by DARPA under agreement number FA8750-19-1-0504. The U.S. Government
> is authorized to reproduce and distribute reprints for Governmental purposes notwithstanding any copyright notation
> thereon.

I can add the agreement number, but the second sentence seems to be referring to published material. Can you confirm that?

**Comment by cfunk1210** [comment]
This is from contracts/legal directly.  You would need to contact them for a confirmation on the scope of that sentence.

**Comment by waxlamp** [comment]
> This is from contracts/legal directly. You would need to contact them for a confirmation on the scope of that sentence.

I am fine with explicitly licensing the government to reproduce already-Apache-licensed code 🤷🏾‍♂️

**Comment by cfunk1210** [comment]
This exact text is probably in a contract somewhere that we have to add it so I don't think we have a choice anyway.

**Comment by waxlamp** [comment]
@cfunk1210 @eswears please take another look.

**Comment by eswears** [comment]
Here's the Acknowledgement of Support and Disclaimer that I got from contracts a while ago: 
Acknowledgement of Support and Disclaimer:
(a) The Contractor shall include an acknowledgment of the Government's support in the publication of any material based on or developed under this contract, stated in the following terms: This material is based upon work supported by the Defense Advanced Research Projects Agency (DARPA) under Contract No. HR001120C0055.
(b) All material, except scientific articles or papers published in scientific journals, must, in addition to any notices or disclaimers by the Contractor, also contain the following disclaimer: Any opinions, findings and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the DARPA.

**Comment by waxlamp** [comment]
> Here's the Acknowledgement of Support and Disclaimer that I got from contracts a while ago:
> Acknowledgement of Support and Disclaimer:
> (a) The Contractor shall include an acknowledgment of the Government's support in the publication of any material based on or developed under this contract, stated in the following terms: This material is based upon work supported by the Defense Advanced Research Projects Agency (DARPA) under Contract No. HR001120C0055.
> (b) All material, except scientific articles or papers published in scientific journals, must, in addition to any notices or disclaimers by the Contractor, also contain the following disclaimer: Any opinions, findings and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the DARPA.

@eswears, if you look at the Files Changed tab, you'll see that I have added language that meets these requirements. Or at least, I've attempted to: if you can take a look and leave a GitHub review either approving, or requesting changes, that would be very helpful. (You can also just message me privately with your review, whatever's easiest for you.)

**Comment by eswears** [comment]
I was thinking this had the contract numbers for both SAIL-ON on LEARN. But it looks like there is only one of them. Can the LEARN contract number also be added here?

**Comment by waxlamp** [comment]
> I was thinking this had the contract numbers for both SAIL-ON on LEARN. But it looks like there is only one of them. Can the LEARN contract number also be added here?

Can you send me the contract number for LEARN? The text I added (from [Chris's comment above](https://github.com/tinker-engine/tinker-engine/pull/134#issuecomment-789035339)) includes an "agreement number" but not a "contract number".

**Review by as6520 — APPROVED** [review]

**Comment by as6520** [comment]
Used the old acknowledgment to verify this https://github.com/tinker-engine/tinker-engine/tree/old-tinker#acknowledgement-of-support-and-disclaimer. So it's LGTM.

**Pull request merged**
