### PR TITLE
Add an action to publish on pypi

### PR DESCRIPTION
**Pull request by as6520**
This PR creates an action to publish tinker-engine on pypi. Depends on #149 

An alpha build for the package is available on https://pypi.org/project/tinker-engine/

### CODE REVIEW

**Review by waxlamp — DISMISSED** [review]
This all looks ok to me. The true test is if it works properly, and if it does, then it's ok with me :)

The only suggestions I have are:
- perhaps you want to keep the caching infrastructure for the pip dependencies if the Poetry action doesn't do it, and if you observe that the build takes a long time
- instead of push-to-tag to release, you may want to look at [intuit/auto](https://intuit.github.io/auto/). I am looking at using this in some of my projects and haven't figured it out quite yet, but it could be a neat way to replace the tag-based workflow.

**Comment by as6520** [comment]
> * perhaps you want to keep the caching infrastructure for the pip dependencies if the Poetry action doesn't do it, and if you observe that the build takes a long time

I had originally retained caching in 78f8483. However, `poetry install` installs the tinker, thus retaining cache might and skipping `poetry install` might cause an older version of the package to run in actions. While this would cause publish action to fail due to version mismatch, it would cause main.yml to start testing an older version of the package. Additionally, since tinker has limited dependency caching doesn't provide a significant benefit in terms of run time.

> * instead of push-to-tag to release, you may want to look at [intuit/auto](https://intuit.github.io/auto/). I am looking at using this in some of my projects and haven't figured it out quite yet, but it could be a neat way to replace the tag-based workflow.

Interesting, could you point me to the workflows that you have created using it. That might be an easier way for me to see how to use it in publish workflow.

**Comment by waxlamp** [comment]
> > * instead of push-to-tag to release, you may want to look at [intuit/auto](https://intuit.github.io/auto/). I am looking at using this in some of my projects and haven't figured it out quite yet, but it could be a neat way to replace the tag-based workflow.
> 
> Interesting, could you point me to the workflows that you have created using it. That might be an easier way for me to see how to use it in publish workflow.

[This project](https://github.com/dandi/dandi-cli) uses it, but I didn't set it up.

**Comment by as6520** [comment]
> > > * instead of push-to-tag to release, you may want to look at [intuit/auto](https://intuit.github.io/auto/). I am looking at using this in some of my projects and haven't figured it out quite yet, but it could be a neat way to replace the tag-based workflow.
> > 
> > 
> > Interesting, could you point me to the workflows that you have created using it. That might be an easier way for me to see how to use it in publish workflow.
> 
> [This project](https://github.com/dandi/dandi-cli) uses it, but I didn't set it up.

Cool will check it out

**Review by waxlamp — APPROVED** [review]

**Pull request merged**
